name: bip39dart
description: bip39 dart implementation
version: 0.0.1
author: Jakub Mirota <mirota.jakub@gmail.com>
homepage: https://github.com/jmirota/bip39dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

